# Формат чатов. Поддерживается PlaceholderAPI
# <player> - ник игрока
# <prefix> - префикс игрока (берется из vault api)
# <suffix> - суффикс игрока (берется из vault api)
# <dph> - плейсхолдер группы
format:
  local: "&aⓁ&f <prefix> &8⋆&f <player>&7:<dph> <message>"
  # Радиус распространения локального чата
  localRadius: 100
  # Если установлено true - весь чат будет глобальным и не будет требовать символа "!"
  forceGlobal: false
  global: "&cⒼ&f <prefix> &8⋆&f <player>&7:<dph> <message>"

# Плейсхолделы для донатов по группам
donatePlaceholders:
  default: "&7"
  admin: "&f&l"

# Настройка ховертекста (текст при наведении на сообщение игрока)
# При включении заменяет логику работы чата, что может сказаться на работе других плагинов, включающих в себя его форматирование.
# Сообщения будут отправляться игрокам от сервера.
hoverText:
  enable: false
  format: |-
    &fИнформация об игроке <player>
    &fРанг: &6%vault_group%
    &fХП: &6%player_health%
    &fОпыт: &6%player_exp%

# Настройки кулдауна
cooldown:
  # Кулдаун для локального чата в милисекундах
  localCooldown: 500
  # Кулдаун для глобального чата в милисекундах
  globalCooldown: 1500
  # Сообщение о кулдауне
  cooldownMessage: "&e[♻]&f Вы слишком быстро пишите! Подождите еще %time%."

# Настройка блокировки чата для новичков
newbieChat:
  # Включен ли newbieChat
  enable: true
  # Кулдаун на чат для новичков в секундах
  newbieCooldown: 600
  # Сообщение для чата для новичков
  newbieChatMessage: "&c[★] &6Подожди! Что-бы написать в чат вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Сообщение для команд для новичков
  newbieCommandMessage: "&c[★] &6Подожди! Что-бы написать данную команды вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Команды, которые будут попадать под newbieChat
  newbieCommands:
    - "/m"
    - "/pm"
    - "/msg"
    - "/t"
    - "/tell"
    - "/w"
    - "/whisper"

# Настройка автосообщений
# Существует только по тому, что это есть в Chatty.
autoMessage:
  # Включел ли autoMessage
  enable: true
  # Выдавать ли их рандомно
  random: true
  # Промежуток между сообщениями в секундах
  messageInterval: 300
  # Сообщения
  messages:
    1:
      - "[PromisedChat] первое авто-сообщение"
    2:
      - "123"
      - "[PromisedChat] второе авто-сообщение"
      - "123"